name = "LEANprj"
version = "0.1.0"
defaultTargets = ["leanprj"]

[[lean_lib]]
name = "LEANprj"

[[lean_exe]]
name = "leanprj"
root = "Main"

[[require]]
name = "mathlib"
git  = "https://github.com/leanprover-community/mathlib4"
rev  = "v4.23.0"
